from __future__ import annotations

import importlib.util
from pathlib import Path
import sys

import pandas as pd


ROOT = Path(__file__).resolve().parents[3]
TASK_DIR = Path(__file__).resolve().parent
DATA = ROOT / "data" / "analysis_ready" / "Fig4"
OUT = ROOT / "outputs" / "Fig4" / "derived" / "current"
SENSITIVITY_SCRIPT = TASK_DIR / "leoro_sensitivity.py"

LUGRE_CACHE = DATA / "lugre_cn0_qc_points.csv.gz"
FIGURE_IONO_SOURCE = DATA / "lugre_cn0_qc_points.csv.gz"

PNG_OUT = OUT / "Fig3_receiver_regime_comparison_no_fengyun_rolling_median_lugre_new_reference_ecef_candidate_right_axis_label_fixed.png"
PDF_OUT = OUT / "Fig3_receiver_regime_comparison_no_fengyun_rolling_median_lugre_new_reference_ecef_candidate_right_axis_label_fixed.pdf"
SUMMARY_OUT = OUT / "Fig3_receiver_regime_comparison_no_fengyun_rolling_median_lugre_new_reference_ecef_source_summary_right_axis_label_fixed.csv"
README_OUT = OUT / "README_Fig3_no_fengyun_rolling_median_new_reference_ecef_right_axis_label_fixed.md"

METHOD_LABEL = "1 Hz median-SNR C/N0 proxy minus centered dynamic rolling-median baseline"
SOURCE_NOTE = (
    "LEO-RO panel a uses SNR-derived delta C/N0 proxy residuals from the rolling-median/local-median baseline; "
    "FengYun is excluded; 0.05 Hz high-pass is retained only as sensitivity/backup."
)


def import_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot import {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def patch_panel_a_right_axis_label(base) -> None:
    def add_right_height_axis_fixed(ax):
        ax.set_yticks([50, 90, 150, 300, 600, 800, 1000])
        ax.set_yticklabels(["50", "90", "150", "300", "600", "800", "1000"], fontsize=6.7)
        ax.yaxis.tick_right()
        ax.yaxis.set_label_position("right")
        ax.set_ylabel("Tangent height (km)", fontsize=7.4, rotation=90, labelpad=3)
        ax.tick_params(
            axis="y",
            right=True,
            labelright=True,
            left=False,
            labelleft=False,
            length=1.9,
            width=0.45,
            colors=base.INK,
            pad=1.5,
        )
        ax.spines["right"].set_visible(True)
        ax.spines["right"].set_color(base.SPINE)
        ax.spines["right"].set_linewidth(0.48)

    base.add_right_height_axis = add_right_height_axis_fixed


def write_readme(summary: pd.DataFrame) -> None:
    leo = summary[(summary["panel"].eq("a LEO-RO")) & (summary["observable"].str.contains("cn0", case=False, na=False))]
    lugre = summary[summary["panel"].eq("a LuGRE")]
    text = f"""# Fig.3 right-axis-label fixed candidate

Generated by `make_fig3_no_fengyun_rolling_median_new_reference_right_axis_label_fixed.py`.

This is a layout-only revision of the no-FengYun rolling-median LuGRE new-reference ECEF Fig.3 candidate.

## Change

- Panel a right-side `Tangent height (km)` label rotation changed from 270 degrees to 90 degrees, with a reduced label pad so the title aligns visually with the right-side labels in panels b and c.
- No data source, filtering, detrending method, statistic, panel content, color, axis range, or source summary logic is changed.

## Outputs

- `{PNG_OUT.name}`
- `{PDF_OUT.name}`
- `{SUMMARY_OUT.name}`

## Data status

- FengYun remains excluded.
- LEO-RO panel a remains the rolling-median/local-median C/N0-proxy residual version, not hp05.
- LuGRE uses the updated WGC receiver reference geometry with ECEF/geographic tangent latitude/longitude and refreshed magnetic latitude / height-layer grouping.

LuGRE panel-a rows: {int(lugre["n"].sum()) if not lugre.empty else 0}
LEO-RO rolling-median panel-a rows: {int(leo["n"].sum()) if not leo.empty else 0}
"""
    README_OUT.write_text(text, encoding="utf-8")


def main() -> None:
    if not SENSITIVITY_SCRIPT.exists():
        raise FileNotFoundError(SENSITIVITY_SCRIPT)
    if not LUGRE_CACHE.exists():
        raise FileNotFoundError(LUGRE_CACHE)

    sens = import_module(SENSITIVITY_SCRIPT, "fig3_leoro_rolling_sensitivity_fixed")
    base = sens.load_base_module()
    patch_panel_a_right_axis_label(base)

    base.LUGRE_CACHE = LUGRE_CACHE
    base.LUGRE_4FITTING_XLSX = FIGURE_IONO_SOURCE
    base.PNG_OUT = PNG_OUT
    base.PDF_OUT = PDF_OUT
    base.SUMMARY_OUT = SUMMARY_OUT
    base.README_OUT = README_OUT

    lugre = base.load_lugre_points()
    events = base.load_leoro_events()
    ground = base.load_ground_ismr()
    rolling = sens.build_rolling_cache(base)

    summary = sens.build_summary(base, lugre, rolling, events, ground, METHOD_LABEL, SOURCE_NOTE, SUMMARY_OUT)
    base.draw_figure(lugre, rolling, events, ground)
    write_readme(summary)

    print(PNG_OUT)
    print(PDF_OUT)
    print(SUMMARY_OUT)
    print(README_OUT)


if __name__ == "__main__":
    main()
